# Generated by Django 4.2 on 2023-04-26 14:51

from django.db import migrations


def create_calendar(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Calendar = apps.get_model("swingtime", "Calendar")
    if not Calendar.objects.count():
        Calendar.objects.create(id=1, name="default calendar", timezone="UTC")


def remove_calendar(apps, schema_editor):
    Calendar = apps.get_model("swingtime", "Calendar")
    Calendar.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("swingtime", "0002_alter_occurrence_options_alter_event_id_and_more"),
    ]

    operations = [
        migrations.RunPython(create_calendar, remove_calendar),
    ]
