# Generated by Django 4.2 on 2023-04-26 14:51

from django.db import migrations


def create_group(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    EventGroup = apps.get_model("swingtime", "EventGroup")
    if not EventGroup.objects.count():
        EventGroup.objects.create(id=1, name="default group", timezone="UTC")


def remove_group(apps, schema_editor):
    EventGroup = apps.get_model("swingtime", "EventGroup")
    EventGroup.objects.filter(pk=1).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("swingtime", "0002_alter_occurrence_options_alter_event_id_and_more"),
    ]

    operations = [
        migrations.RunPython(create_group, remove_group),
    ]
