# Generated by Django 4.2 on 2023-05-01 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swingtime", "0004_event_calendar"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"verbose_name": "event", "verbose_name_plural": "events"},
        ),
        migrations.AddField(
            model_name="event",
            name="url",
            field=models.URLField(max_length=256, null=True, verbose_name="Event URL"),
        ),
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Description"
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="swingtime.eventtype",
                verbose_name="Event Type",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="title",
            field=models.CharField(max_length=32, verbose_name="Title"),
        ),
    ]
