# Generated by Django 4.2.1 on 2023-05-10 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("swingtime", "0005_alter_event_options_event_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="occurrence",
            name="end_time",
            field=models.DateTimeField(db_index=True, verbose_name="end time"),
        ),
        migrations.AlterField(
            model_name="occurrence",
            name="start_time",
            field=models.DateTimeField(db_index=True, verbose_name="start time"),
        ),
    ]
