# Generated by Django 4.2.1 on 2023-05-17 08:16

import django.db.models.deletion
import timezone_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="Title")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Description"
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=256, null=True, verbose_name="Event URL"
                    ),
                ),
            ],
            options={
                "verbose_name": "event",
                "verbose_name_plural": "events",
            },
        ),
        migrations.CreateModel(
            name="EventType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abbr",
                    models.CharField(
                        max_length=4, unique=True, verbose_name="Abbreviation"
                    ),
                ),
                ("label", models.CharField(max_length=50, verbose_name="Lbel")),
            ],
            options={
                "verbose_name": "Event type",
                "verbose_name_plural": "Event types",
            },
        ),
        migrations.CreateModel(
            name="Occurrence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_time",
                    models.DateTimeField(db_index=True, verbose_name="start time"),
                ),
                (
                    "end_time",
                    models.DateTimeField(db_index=True, verbose_name="end time"),
                ),
                (
                    "event",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="jivetime.event",
                        verbose_name="event",
                    ),
                ),
            ],
            options={
                "verbose_name": "occurrence",
                "verbose_name_plural": "occurrences",
                "ordering": ("start_time", "end_time"),
                "base_manager_name": "objects",
            },
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("note", models.TextField(verbose_name="note")),
                (
                    "created",
                    models.DateTimeField(auto_now_add=True, verbose_name="created"),
                ),
                ("object_id", models.PositiveIntegerField(verbose_name="object id")),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="content type",
                    ),
                ),
            ],
            options={
                "verbose_name": "note",
                "verbose_name_plural": "notes",
            },
        ),
        migrations.CreateModel(
            name="EventGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("timezone", timezone_field.fields.TimeZoneField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="event",
            name="event_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="jivetime.eventtype",
                verbose_name="Event Type",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="jivetime.eventgroup"
            ),
        ),
    ]
